#include: package:flutter_lints/flutter.yaml
include: package:ubuntu_lints/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.config.dart
    - build/**
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    eol_at_end_of_file: true
    avoid_unused_constructor_parameters: true
    avoid_redundant_argument_values: true
    use_super_parameters: true
    unnecessary_late: true
    collection_methods_unrelated_type: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_shadowing_type_parameters: true
    unnecessary_parenthesis: true
    unnecessary_this: true
    require_trailing_commas: true
    sort_constructors_first: true
    unawaited_futures: warn
    use_named_constants: true