name: nestra
description: "Run web (PWA) apps like native desktop applications with isolation, tray integration, and notifications."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  intl: ^0.20.2
  ubuntu_localizations: ^0.5.2+2
  cupertino_icons: ^1.0.8
  package_info_plus: ^9.0.0
  local_notifier: ^0.1.6
  window_manager: ^0.5.1
  webview_cef: ^0.2.2
  tray_manager: ^0.5.1
  launch_at_startup: ^0.5.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  args: ^2.7.0
  xdg_icons: ^0.1.2
  ubuntu_widgets: ^0.7.3
  ubuntu_service: ^0.4.0+1
  ubuntu_logger: ^0.2.1+1
  gtk: ^2.1.0
  http: ^1.5.0
  html: ^0.15.6
  desktop_drop: ^0.6.1
  flutter_svg: ^2.2.1
  image: ^4.5.4
  hive_ce: ^2.12.0
  hive_ce_flutter: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ubuntu_lints: ^0.4.1+1
  build_runner: ^2.8.0
  injectable_generator: ^2.8.1
  freezed: ^3.2.3
  hive_ce_generator: ^1.11.0
  json_serializable: ^6.9.0

dependency_overrides:
  build: ^4.0.0
  analyzer: ^7.7.1
  _fe_analyzer_shared: ^85.0.0
  source_gen: ^3.1.0
  hive_ce_generator: 1.9.3

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/branding/