name: nestra
description: "Run web (PWA) apps like native desktop applications with isolation, tray integration, and notifications."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  package_info_plus: ^9.0.0
  local_notifier: ^0.1.6
  window_manager: ^0.5.1
  webview_cef: ^0.2.2
  tray_manager: ^0.5.1
  launch_at_startup: ^0.5.1
  get_it: ^7.7.0
  injectable: ^2.4.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  logger: ^2.4.0
  freezed_annotation: ^2.4.1
  args: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  freezed: ^2.5.2

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/launch/